lhcb_problemdb/problemdb/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url

from django.views.generic.simple import redirect_to

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),

    url(r'^report/$', redirect_to, {'url': '/report/active/'}),
    url(r'^report/active/$', views.problems_print),

    url(r'^problems/new/$', views.problem_new, name='problem_new'),

    url(r'^search/run/$', views.problem_search_run, name='problem_search_run'),

    url(r'^search/$', views.problem_search, name='problem_search'),

    url(r'^problems/(?P<problem_id>\d+)/$', views.problem, name='problem_detail'),

    url(r'^problems/(?P<problem_id>\d+)/undo/$', views.problem_undo, name='problem_undo'),

    url(r'^problems/(?P<problem_id>\d+)/edit/$', views.problem_edit, name='problem_edit'),
    
    url(r'^problems/(?P<problem_id>\d+)/close/$', views.problem_close, name='problem_close'),

    url(r'^comments/(?P<problem_id>\d+)/$', views.comments, name='comments'),
    
    url(r'api/search/$', views.api_search),
    url(r'api/systems/$', views.api_systems),
    url(r'api/problems/$', views.api_create_problem),
    url(r'api/activity/$', views.api_activity)
)

lhcb_problemdb/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.contrib import admin

from django.conf import settings

from django.contrib.auth.views import login, logout

admin.autodiscover()

urlpatterns = patterns('',
    (r'', include('problemdb.urls')),

    (r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login/$',  login, dict(template_name="accounts/login.html"), name="accounts_login"),
    url(r'^accounts/logout/$', logout, dict(next_page="/"), name="accounts_logout"),

)

# Urls available only for development
if settings.DEBUG:

    #from django.contrib.auth.views import login, logout

    #url(r'^accounts/login/$',  login, dict(template_name="accounts/login.html"), name="accounts_login"),
    #url(r'^accounts/logout/$', logout, dict(next_page="/"), name="accounts_logout"),
    
    # Serve static files iwth Django only in DEBUG mode.
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True
        }),
    )

lhcb_problemdb/problemdb/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.contrib.auth.models import User

class Severity(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    ordering = models.IntegerField(default=0, help_text="Items with a higher value appear first in the lists. Use a negative number to move an item to the last position.")
    # TODO: Add an attribute for specifying that the severity should be reported

    assessed = models.BooleanField(default=False, help_text="Problems with this severity can be closed")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "severities"
        ordering = ("-ordering", "name")

class System(models.Model):
    name = models.CharField(max_length=100)
    #alias = models.SlugField()
    description = models.TextField(null=True, blank=True)
    ordering = models.IntegerField(default=0, help_text="Items with a higher value appear first in the lists. Use a negative number to move an item to the last position.")
    visible = models.BooleanField(default=True, help_text="Display this system on the home page")

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ("-ordering", "name")


class Problem(models.Model):
    """
    A record of a problem
    
    The author can be null when the problem is created by a non-authenticated
    user.
    """
    author = models.ForeignKey(User, related_name="problems", null=True, blank=True)
    system = models.ForeignKey(System, related_name="problems")
    severity = models.ForeignKey(Severity, related_name="problems")

    added_at = models.DateTimeField(default=datetime.datetime.now)
    started_at = models.DateTimeField(default=datetime.datetime.now)
    ended_at = models.DateTimeField(null=True, blank=True)

    title = models.CharField(max_length=300)

    author_name = models.CharField(max_length=300, null=True, blank=True, 
        help_text="Name of the author used when the problem is created by an unauthenticated user.")

    def get_author_full_name(self):
        return self.author  and self.author.get_full_name() or self.author_name

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('problem_detail', [str(self.id)])

    def is_assessed(self):
        """
        States if a problem has been assessed and an end date can be set.

        A problem is assessed when it has a severity that has the `assessed`
        attribute.
        """
        return self.severity.assessed

    def save(self, *args, **kwargs):
        """
        Validates the following restrictions before saving the problem:
        
         - The severity must be assessed before closing
         - The author name must be specified if the author is null.
        """
        
        if not self.author and not self.author_name:
            raise Exception("The author name must be used for problems from unauthenticated users")

        if not self.is_assessed() and self.ended_at:
            raise Exception("End date can be set only once the severity has been assessed")

        if self.ended_at and self.ended_at < self.started_at:
            raise Exception("The end date must be after the start date of the problem")

        super(Problem, self).save(*args, **kwargs)

    def close(self, ended_at):
        """
        Closes the problem setting its end date.
        """
        self.ended_at = ended_at

    def report_changes(self, user, changed_data):
        """
        Creates a comment with the report of the changes made by an user.

        Finds the differences between the current model data and the 
        argument `changed_data`.

        user: A models.User instance
        changed_data: A dictionary with the changed fields (keys) and the
              modified data (values)
        """
        if not changed_data:
            return

        field_name = lambda s: s.title().replace("_", " ")

        message = "Updated the problem report and changed %d fields (%s)" % (
            len(changed_data),
            ", ".join([field_name(field) for field in changed_data])
        )

        message_detail = []

        # Report the detailed changes for the following fields
        detailed_fields = ("severity", "ended_at")
        for field in detailed_fields:
            if field in changed_data:

                text = "'%s' changed from '%s' to '%s'" % (field_name(field),
                    changed_data[field][0] or "(empty)",
                    changed_data[field][1] or "(empty)")

                message_detail.append(text)

        comment = Comment()
        comment.problem = self
        comment.author = user
        comment.comment = "%s.\n%s" % (message, ". ".join(message_detail))
        comment.save()


class Comment(models.Model):
    problem = models.ForeignKey(Problem, related_name="comments")
    author = models.ForeignKey(User, related_name="comments", null=True, blank=True)
    added_at = models.DateTimeField(default=datetime.datetime.now)
    comment = models.TextField()
    link = models.URLField(null=True, blank=True, verify_exists=False)
    
    author_name = models.CharField(max_length=300, null=True, blank=True, 
        help_text="Name of the author used when the problem is created by an unauthenticated user.")

    def get_author_full_name(self):
        return self.author  and self.author.get_full_name() or self.author_name

    def save(self, *args, **kwargs):
        """
        Validates the following restrictions before saving the problem:
        
         - The severity must be assessed before closing
         - The author name must be specified if the author is null.
        """
        
        if not self.author and not self.author_name:
            raise Exception("The author name must be used for problems from unauthenticated users")

        super(Comment, self).save(*args, **kwargs)

    class Meta:
        ordering = ["added_at"]


class ApiKey(models.Model):
    """
    An ApiKey is the password that external applications use to access
    the problem database. 
    """
    value = models.CharField(max_length=200)

lhcb_problemdb/problemdb/forms.py
# -*- coding: utf-8 -*-

import datetime

from django import forms
from django.forms import ModelForm

from django.conf import settings

from models import Comment, Problem, Severity

class ProblemForm(ModelForm):
    started_at = forms.SplitDateTimeField(label="Started at", required=True,
        initial=datetime.datetime.now,
        widget = forms.widgets.SplitDateTimeWidget(
            date_format=settings.FORM_DATE_FORMAT,
            time_format=settings.FORM_TIME_FORMAT,
        ))

    ended_at = forms.SplitDateTimeField(label="Ended at", required=False,
        widget = forms.widgets.SplitDateTimeWidget(
            date_format=settings.FORM_DATE_FORMAT,
            time_format=settings.FORM_TIME_FORMAT,
        ))

    def clean(self):

        data = self.cleaned_data

        ended_at = data.get("ended_at")
        severity = data.get("severity")

        if ended_at and not severity.assessed:
            valid_severities = Severity.objects.filter(assessed__exact = True).all()
            
            raise forms.ValidationError("The end date can be set only once the severity has been assessed. Change the severity to '%s' or do not enter an end date. " % valid_severities[0].name)
        
        return data

    def clean_ended_at(self):        
        started_at = self.cleaned_data.get("started_at")
        ended_at = self.cleaned_data.get("ended_at")
        if ended_at and ended_at < started_at:
            raise forms.ValidationError("The end date must be after the start date")

        return ended_at

    class Meta:
        model = Problem
        fields = ('title', 'system', 'severity', 'started_at', 'ended_at')


class ProblemCreateForm(ProblemForm):

    initial_comment = forms.CharField(required=True, widget=forms.Textarea)
    link = forms.URLField(required=False, label="Logbook link")
    class Meta(ProblemForm.Meta):
        fields = ('title', 'system', 'severity', 'started_at', 'ended_at', 'initial_comment')

class ProblemCloseForm(forms.Form):
    comment = forms.CharField(required=True, widget=forms.Textarea)
    ended_at = forms.SplitDateTimeField(label="Ended at", required=True,
        initial=datetime.datetime.now,
        widget = forms.widgets.SplitDateTimeWidget(
            date_format=settings.FORM_DATE_FORMAT,
            time_format=settings.FORM_TIME_FORMAT,
        ))
    link = forms.URLField(required=False, label="Logbook link")


    def __init__( self, problem, *args, **kwargs ): 
        """
        Using additional argument for validating the end date with the
        problem's start date
        """
        super(ProblemCloseForm, self ).__init__( *args, **kwargs) 
        self.problem = problem

    def clean_ended_at(self):
        ended_at = self.cleaned_data.get("ended_at")
        if ended_at < self.problem.started_at:
            raise forms.ValidationError("The end date must be after the start date") 

        return ended_at

class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('comment','link')

class ApiProblemCreateForm(ProblemCreateForm):
    started_at = forms.DateTimeField(label="Started at", required=True,
        initial=datetime.datetime.now)
    system_name = forms.CharField(required=False, widget=forms.Textarea)
    author_name = forms.CharField(required=True, widget=forms.Textarea)

lhcb_problemdb/templates/problemdb/index.html
{% extends "base.html" %} 

{% load layout %}

{% block content %}


<h3>Browse problems by system</h3>

<table width="50%">
{% for row in systems|tablecols:6 %}
    <tr>
    {% for system in row %}
        <td>
            <a href="{% url problem_search %}?system={{ system.id }}">{{ system.name }}</a> <!-- ({{ system.num_problems }}) -->
        </td>
    {% endfor %}
    </tr>
{% endfor %}
</table>


<h3>Active problems <a href="/report/active/" class="lhcb-button lhcb-button-print">Print</a></h3>
{% if active_problems %}
{% problem_table active_problems %}
{% else %}
<p>There are no active problems right now.</p>
{% endif %}

<h3>Reports</h3>
{% if reports %}
{% problem_table reports %}
{% else %}
<p>There are no reports.</p>
{% endif %}

<h3>Recently reported</h3>
{% if recent_problems %}
{% problem_table recent_problems %}
{% else %}
<p>There are no recently reported problems.</p>
{% endif %}

<h3>Problems by run</h3>
<p>Find the problems affecting a run.</p>
<form action="/search/run/">
<label>Run number 
	<input type="text" value="" name="run_id" />
</label>
<button type="submit">Search</button>
</form>

<h3>Last comments</h3>
{% if comments %}

{% for comment in comments %}
    <div class="comment" id="comment-{{ comment.id }}">
    <p class="meta">#<a href="#comment-{{ comment.id }}">{{ forloop.counter }}</a> by <strong>{{ comment.get_author_full_name }}</strong> on {{ comment.added_at|date }}</p>

    {{ comment.comment|removetags:"b span"|urlizetrunc:50|linebreaks}}

    {% if comment.link %}
    <p><a href="{{ comment.link }}" target="_blank">Logbook link</a></p>
    {% endif %}

    
    </div>
{% endfor %}


{% else %}
<p>There are no reports.</p>
{% endif %}


{% endblock %}
{% block script %}

<script type="text/javascript">

$(function() {
    $(".lhcb-button").button();

    $(".lhcb-button-print").button({ 
        icons: {primary:'ui-icon-print'},
        atext: false
    });

})

</script>
{% endblock %}
{% block head %}
<style type="text/css" media="screen">


</style>
{% endblock %}

lhcb_problemdb/templates/problemdb/problem_close.html
{% extends "base.html" %}

{% block page_title %}{{ problem.title }} - {% endblock %}
{% block header_title %}{% endblock %}

{% block content %}

<h2>Problem <a href="{{ problem.get_absolute_url }}">{{ problem.id}}</a>: {{ problem.title }}</h2>

<table class="problem-detail" width="100%">
<tr>
<td valign="top" width="20%">
<dl>

<dt>System</dt>
<dd>{{ problem.system }}</dd>

<dt>Severity</dt>
<dd>{{ problem.severity }}</dd>


<dt>Start date</dt>
<dd><span title="{{ problem.started_at|date }}">{{ problem.started_at|date }}</span></dd>

<dt>End date</dt>
<dd>

{% if problem.ended_at %}
<span title="{{ problem.ended_at }}">{{ problem.ended_at|date }}</span>
{% else %}
<em>Problem is still open</em>
{% endif %}
</dd>

<dt>Reported by</dt>
<dd><em>{{ problem.get_author_full_name }}</em> on {{ problem.added_at|date }}</dd>


</dl>

{% if user.is_authenticated %}

<p><a href="{% url problem_edit problem.id %}">Edit problem report</a></p>

<p><a href="#add-comment">Add a comment</a></p>

{% endif %}


</td>
<td width="80%">

{% if problem.is_assessed %}

<p>You can <strong>close</strong> the problem now, please be sure that its severity has been assessed.</p>

{# The action is the same URI, for editing or creating a problem #}
<form action="" method="post">
<table>

{% for field in form %}
    <tr>
        <th>{{ field.label_tag }}</th>
        <td>{{ field }}</td>
        <td>{{ field.errors }}</td>
    </tr>
{% endfor %}
<tr><td colspan="2" align="center"><input type="submit" value="Close the problem" />

</td></tr>
</table>
</form>

{% else %}

<p>You <strong>can't close</strong> the problem now because its severity is <em>{{ problem.severity }}</em>. Please change be sure that it has been assessed, change it and then close the problem.</p>

{% endif %}

</td>
</tr>
</table>



{% endblock %}
{% block head %}
<style type="text/css" media="screen">

form {
	padding: 0.5em;
}

/**
Change the width of the form elements using the id attribute set by Django. Not elegant, though.
*/
form #id_comment, #id_link {
    width: 40em;
}

.hasDatepicker {
    width: 6em;
}

#id_ended_at_1 {
    width: 3em;
}

</style>
{% endblock %}
{% block script %}
<script type="text/javascript">

var messages = [
    {arg: "new-comment", text: "Comment added"},
    {arg: "new-problem", text: "Problem created"},
    {arg: "update-problem", text: "Problem updated"},
];

jQuery.each(messages, function() {
    if  (getQueryString(this.arg)){
        lhcb.message(this.text);
    }
})


$(function() {

    /**
     *
     *
     */
    var mk_datepicker = function(elm){
        $(elm).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy-mm-dd',
            duration: 100,
            showOn: "button",
            //buttonText: "Choose"
        });
    }

    mk_datepicker("#id_ended_at_0");
});

</script>
{% endblock %}

lhcb_problemdb/templates/problemdb/problem_detail.html
{% extends "base.html" %}

{% block page_title %}{{ problem.title }} - {% endblock %}
{% block header_title %}{% endblock %}

{% block content %}

<h2>Problem <a href="{{ problem.get_absolute_url }}">{{ problem.id}}</a>: {{ problem.title }}</h2>

<table class="problem-detail" width="100%">
<tr>
<td valign="top" width="20%">
<dl>

<dt>System</dt>
<dd>{{ problem.system }}</dd>

<dt>Severity</dt>
<dd>{{ problem.severity }}</dd>


<dt>Start date</dt>
<dd><span title="{{ problem.started_at|date }}">{{ problem.started_at|date }}</span></dd>

<dt>End date</dt>
<dd>

{% if problem.ended_at %}
<span title="{{ problem.ended_at }}">{{ problem.ended_at|date }}</span>
{% else %}
<em>Problem is still open</em>
{% if user.is_authenticated %}
<br /><a href="{% url problem_close problem.id %}">Close it</a>
{% endif %}

{% endif %}
</dd>


<dt>Runs affected</dt>
<dd id="problem-runs">
</dd>


<dt>Reported by</dt>
<dd><em>{{ problem.get_author_full_name }}</em> on {{ problem.added_at|date }}</dd>


</dl>

{% if user.is_authenticated %}

{% if not problem.ended_at %}
<p><a href="{% url problem_close problem.id %}">Close the problem</a></p>
{% endif %}



<p><a href="{% url problem_edit problem.id %}">Edit problem report</a></p>

<p><a href="#add-comment">Add a comment</a></p>

{% endif %}


</td>
<td width="80%" valign="top">

<h3>Comments</h3>
<div class="comments">

{% if comments|length %}

<!--<h3>{{ comments|length }} comment{{ comments|length|pluralize }}</h3>-->

{% for comment in comments %}
    <div class="comment" id="comment-{{ comment.id }}">
    <p class="meta">#<a href="#comment-{{ comment.id }}">{{ forloop.counter }}</a> by <strong>{{ comment.get_author_full_name }}</strong> on {{ comment.added_at|date }}</p>

    {{ comment.comment|removetags:"b span"|urlizetrunc:50|linebreaks}}

    {% if comment.link %}
    <p><a href="{{ comment.link }}" target="_blank">Logbook link</a></p>
    {% endif %}

    
    </div>
{% endfor %}

{% else %}

<div class="comment">
<p><em>No comments have been published.</em></p>
</div>

{% endif %}


{% if user.is_authenticated %}
<form action="{% url comments problem.id %}" method="post" id="add-comment">

{% if comment_form.comment.errors %}

<ul class="errorlist">
    <li>The comment could not be added. Please review the errors below.</li>
</ul>
{% endif %}

{{ comment_form.comment }}
{{ comment_form.comment.errors }}

<br />
<p>Logbook link:<br /> {{ comment_form.link }} </p>

{{ comment_form.link.errors }}


<p><input type="submit" value="Add your comment" /></p>
</form>

{% else %}
<p>You can <a href="{% url accounts_login %}?referrer=1">sign in</a> and add comments to this problem.</p>
{% endif %}

</div>



</td>
</tr>
</table>



{% endblock %}
{% block head %}
<style type="text/css" media="screen">

form {
    padding: 0.5em;
}

/**
Change the width of the form elements using the id attribute set by Django. Not elegant, though.
*/
form #id_comment, #id_link {
    width: 40em;
}

</style>
{% endblock %}
{% block script %}
<script type="text/javascript" src="/media/jquery.textarea-expander.js"></script>
<script type="text/javascript">

var messages = [
    {qarg: "new-comment", text: "Comment added"},
    {qarg: "new-problem", text: "Problem created"},
    {qarg: "update-problem", text: "Problem updated"}
];

jQuery.each(messages, function() {
    if  (getQueryString(this.qarg)){
        lhcb.message(this.text);
    }
})

var runsAffected = function(container, startTime, endTime){
    container = $(container);
    var uri_search = "{{ RUNDB_URI_API_SEARCH }}";
    var uri_run = "{{ RUNDB_URI_RUN }}";
    var args = {
        "partition": "LHCb",
        "destination": "OFFLINE",
        "starttime": startTime,
        "endtime": endTime,
        "rows": 999999
    };
    $.get(uri_search, args, function(data){
        if (!data.totalResults){
            container.text("There are no runs affected by this problem");
            return;
        }
        container.empty();

        var start_run = data.runs[data.runs.length - 1];
        var end_run =  data.runs[0];

        if (data.runs.length < 5) {
            var runContainer = $("<ul></ul>").appendTo(container);
            listRuns(runContainer, startTime, endTime, data.totalResults);
        } else {
            var range = $("<span>" + start_run.runid + " - " + end_run.runid + "</span>");
            container.append(range);

            var linkMore = $("<br /><a>Complete list (" + data.totalResults + " runs)</a>");
            container.append(linkMore);
            var runContainer = $("<ul></ul>").appendTo(container);
            linkMore.click(function(){
                listRuns(runContainer, startTime, endTime, data.totalResults);
            })
        }
        return;
    }, "jsonp")
}

var listRuns = function(container, startTime, endTime, rows){
    container = $(container);
    var uri_search = "{{ RUNDB_URI_API_SEARCH }}";
    var uri_run = "{{ RUNDB_URI_RUN }}";
    var args = {
        "partition": "LHCb",
        "destination": "OFFLINE",
        "starttime": startTime,
        "endtime": endTime,
        "rows": (rows || '')
    };
    $.get(uri_search, args, function(data){
        if (!data.totalResults){
            return;
        }
        container.empty();

        var ul = container;
        $.each(data.runs, function(i, item){
            var link = uri_run + item.runid;
            //var run = "<li><a target='_blank' href='" + link +"'>" + item.runid + "</a></li>";
            //$("#problem-runs").append(run);
            ul.append("<li><a target='_blank' href='" + link +"'>" + item.runid + "</a></li>");
        });
        var remaining = (data.totalResults - data.runs.length);
        if (remaining > 0){
            var linkMore = $("<a>" + remaining + " more runs affected</a>");
            linkMore.click(function(){
                runsAffected(container, startTime, endTime, data.totalResults);
            })
            ul.append(linkMore.wrap("<li />"));
        }
    }, "jsonp")
}


$(function(){
    runsAffected("#problem-runs",
            "{{ problem.started_at|date:"Y-m-d\TH:i:s" }}",
            "{{ problem.ended_at|date:"Y-m-d\TH:i:s" }}");



    $('#id_comment').TextAreaExpander(175, 400);
})

</script>
{% endblock %}

lhcb_problemdb/templates/problemdb/problem_form.html
{% extends "base.html" %}
{# Form for editing or reporting a new problem #}
{% block page_title %}{{ message_title }} {% endblock %}
{% block header_title %}{% endblock %}

{% block content %}

<h2>{{ message_title }}</h2>


{% if form.errors %}
<ul class="errorlist">
    <li>The problem report could not be saved. Please review the errors below.</li>
</ul>

{{ form.non_field_errors }}

{% endif %}

{# The action is the same URI, for editing or creating a problem #}
<form action="" method="post">
<table>
    <tr>
        <th>{{ form.title.label_tag }}</th>
        <td>{{ form.title }}</td>
        <td>{{ form.title.errors }}</td>
    </tr>

    <tr>
        <th>{{ form.system.label_tag }}</th>
        <td>{{ form.system }}</td>
        <td>{{ form.system.errors }}</td>
    </tr>
    <tr>
        <th>{{ form.severity.label_tag }}</th>
        <td>{{ form.severity }}</td>
        <td>{{ form.severity.errors }}</td>
    </tr>
    <tr>
        <th>{{ form.started_at.label_tag }}</th>
        <td>{{ form.started_at }}</td>
        <td>{{ form.started_at.errors }}</td>
    </tr>
    <tr>
        <th>{{ form.ended_at.label_tag }}</th>
        <td>{{ form.ended_at }}</td>
        <td>{{ form.ended_at.errors }}</td>
    </tr>
    <tr>
        <th></th>
        <td>Choose the dates based on a range of runs</td>
        <td></td>
    </tr>
    <tr>
        <th></th>
        <td>From run <input type="text" id="run_start" class="run_number"/> to <input type="text" id="run_end" class="run_number"/>
        <button type="button" id="_run_date_search">Search</button></td>
        <td></td>
    </tr>
    <tr>
        <th>{{ form.initial_comment.label_tag }}</th>
        <td>{{ form.initial_comment }}</td>
        <td>{{ form.initial_comment.errors }}</td>
    </tr>
    <tr>
        <th>{{ form.link.label_tag }}</th>
        <td>{{ form.link }}</td>
        <td>{{ form.link.errors }}</td>
    </tr>

<tr><td colspan="2" align="center"><input type="submit" value="Save" />

</td></tr>
</table>
</form>

{% endblock %}

{% block script %}
<script type="text/javascript" src="/media/jquery.textarea-expander.js"></script>
<script type="text/javascript">
    $(function() {

        /**
         *
         *
         */
        var mk_datepicker = function(elm){
            $(elm).datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: 'yy-mm-dd',
                duration: 100,
                showOn: "button"
            });
        }
        mk_datepicker("#id_started_at_0");
        mk_datepicker("#id_ended_at_0");

        var date_from_run = function(form_element, run, date_field){
            if (!run){
                return;
            }

            var uri_run = "http://lbrundb.cern.ch/api/run/" + run + "/?callback=?";
            $.getJSON(uri_run, function(data){
                var datetime = data[date_field].split("T");

                $(form_element + '_0').val(datetime[0]);
                $(form_element + '_1').val(datetime[1]);
            })
        }

        var search_dates = function(){
            var run_start = $('#run_start');
            var run_end = $('#run_end');
            date_from_run('#id_started_at', run_start.val(), 'starttime');
            date_from_run('#id_ended_at', run_end.val(), 'endtime');
        }

        $('#_run_date_search').click(search_dates);
        $('#run_end').blur(search_dates);

        $('#id_initial_comment').TextAreaExpander(175, 400);

    });
</script>
{% endblock %}

{% block head %}
<style type="text/css" media="screen">

/**
Change the width of the form elements using the id attribute set by Django. Not elegant, though.
*/
form #id_title {
    width: 30em;
}

form #id_initial_comment, form #id_link  {
    width: 40em;
}

.hasDatepicker {
    width: 6em;
}

#id_started_at_1, #id_ended_at_1 {
    width: 4em;
}

form .run_number {
    width: 4em;
}

</style>
{% endblock %}

lhcb_problemdb/templates/problemdb/problem_table.html
{# Inclusion tag for showing a table of problems #}
<table class="problems">
<thead>
<tr>
<th width="3%" align="right">#</th>
<th width="37%">Problem</th>
<th width="15%">System</th>
<th width="15%">Severity</th>
<th width="15%">Started</th>
<th width="15%">Ended</th>
</tr>
</thead>
<tbody>
{% for problem in problems %}
<tr class="{% cycle 'odd' 'even' %}">
<td align="right"><a href="{{ problem.get_absolute_url }}">{{ problem.id }}</a></td>
<td><a href="{{ problem.get_absolute_url }}">{{ problem.title }}</a></td>
<td>{{ problem.system }}</td>
<td>{{ problem.severity }}</td>
<td>{{ problem.started_at|date }}</td>
<td>{{ problem.ended_at|date }}</td>
</tr>
{% endfor %}
</tbody>
</table>